# Generated by Django 4.0 on 2025-12-23 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='コメント内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='accounts.customuser', verbose_name='投稿者')),
            ],
            options={
                'verbose_name': '募集',
                'verbose_name_plural': '募集',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('recruitment', '募集'), ('comment', 'コメント'), ('user', 'ユーザー')], max_length=20, verbose_name='通報対象タイプ')),
                ('reason', models.CharField(choices=[('spam', 'スパム・宣伝'), ('harassment', '嫌がらせ・誹謗中傷'), ('inappropriate', '不適切な内容'), ('fraud', '詐欺・なりすまし'), ('other', 'その他')], max_length=20, verbose_name='通報理由')),
                ('detail', models.TextField(blank=True, verbose_name='詳細')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='対応済み')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='対応日時')),
                ('resolution_note', models.TextField(blank=True, verbose_name='対応メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='通報日時')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='wvapp.comment', verbose_name='通報されたコメント')),
                ('recruitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='wvapp.recruitment', verbose_name='通報された募集')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to='accounts.customuser', verbose_name='通報されたユーザー')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reports', to='accounts.customuser', verbose_name='通報者')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to='accounts.customuser', verbose_name='対応した管理者')),
            ],
            options={
                'verbose_name': '通報',
                'verbose_name_plural': '通報',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wvapp.recruitment', verbose_name='募集'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.customuser', verbose_name='投稿者'),
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_good', models.BooleanField(verbose_name='グッド評価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='評価日時')),
                ('session_key', models.CharField(max_length=40, verbose_name='セッションキー')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='accounts.customuser', verbose_name='評価されたユーザー')),
            ],
            options={
                'verbose_name': '評価',
                'verbose_name_plural': '評価',
                'unique_together': {('rated_user', 'session_key')},
            },
        ),
    ]
