# Generated by Django 4.0 on 2025-12-23 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('wvapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userrating',
            name='rater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='accounts.customuser', verbose_name='評価者'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='セッションキー'),
        ),
    ]
