# Generated by Django 4.0 on 2025-12-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wvapp', '0002_alter_userrating_unique_together_userrating_rater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='reason',
            field=models.TextField(blank=True, verbose_name='評価理由'),
        ),
    ]
